# -*- coding: utf-8 -*-
"""BS-RoFormer_wcss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xh8OGfnwYDmS6BPuxL9T_13v87TuWPxv
"""

import torch
import yaml
from pathlib import Path
import sys
import numpy as np
import soundfile as sf
import time
import json 
import os

BASE_DIR=Path("/home/wojgrz4918/bs_roformer")
CONFIG_PATH = BASE_DIR/"model_files/config_bs_roformer_384_8_2_485100.yaml"
CHECKPOINT_PATH = BASE_DIR/"model_files/model_bs_roformer_ep_17_sdr_9.6568.ckpt"
AUDIO_DIR_PATH = Path( os.environ.get("AUDIO_DIR_PATH", BASE_DIR / "test_wav"))
OUTPUT_DIR_PATH =Path( os.environ.get("OUTPUT_DIR_PATH", BASE_DIR / "output-dir"))
REPO_PATH = BASE_DIR/"Music-Source-Separation-Training"
INFERENCE_TIMES_PATH = Path(os.environ.get("INFERENCE_TIMES_PATH",BASE_DIR / "inference_times.json"))

STEMS = ["drums", "bass", "other", "vocals"]

if str(REPO_PATH) not in sys.path:
    sys.path.insert(0, str(REPO_PATH))

from models.bs_roformer.bs_roformer import BSRoformer

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("PyTorch:", torch.__version__)
print("CUDA avaiable:", torch.cuda.is_available())
print("Device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("GPU memory:",round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2),"GB")

if not CONFIG_PATH.exists():
    raise FileNotFoundError(f"Brak configu: {CONFIG_PATH}")

if not CHECKPOINT_PATH.exists():
    raise FileNotFoundError(f"Brak checkpointu: {CHECKPOINT_PATH}")

with open(CONFIG_PATH, "r") as f:
    config = yaml.load(f, Loader=yaml.FullLoader)

model_config = config["model"]
SAMPLE_RATE = config["audio"]["sample_rate"]
CHUNK_SIZE = config["audio"]["chunk_size"]

print("Model config:", model_config)
print("Sample rate:", SAMPLE_RATE)
print("Chunk size:", CHUNK_SIZE)
print("Chunk seconds:", CHUNK_SIZE / SAMPLE_RATE)

print("Building model")

model = BSRoformer(**model_config)

print("Loading checkpoint")

checkpoint = torch.load(
    CHECKPOINT_PATH,
    map_location="cpu"
)

if isinstance(checkpoint, dict) and "state_dict" in checkpoint:
    state_dict = checkpoint["state_dict"]
else:
    state_dict = checkpoint

state_dict = {
    k.replace("module.", "", 1): v
    for k, v in state_dict.items()
}

missing, unexpected = model.load_state_dict(state_dict, strict=False)

print("Missing keys:", missing)
print("Unexpected keys:", unexpected)

if missing or unexpected:
    raise RuntimeError(
        "Checkpoint nie pasuje do modelu. Sprawdź wersję repozytorium i config."
    )

model = model.to(device)
model.eval()

print("Model device:", next(model.parameters()).device)

def load_audio(path, sample_rate=SAMPLE_RATE):
    audio, sr = sf.read(str(path),dtype="float32",always_2d=True)

    if sr != sample_rate:
        raise ValueError( f"Expected sample rate {sample_rate}, got {sr} for {path}")

    audio = audio.T

    if audio.shape[0] == 1:
        audio = np.repeat(audio, 2, axis=0)

    if audio.shape[0] > 2:
        audio = audio[:2]

    return torch.from_numpy(audio)

@torch.inference_mode()
def separate_audio(
    audio,
    model,
    chunk_size=CHUNK_SIZE,
    overlap=0.5,
):

    model.eval()

    audio = audio.float()

    if audio.ndim != 2:
        raise ValueError(
            f"Expected audio [channels, samples], got {audio.shape}"
        )

    channels, total_samples = audio.shape

    if channels != 2:
        raise ValueError(
            f"BS-Roformer config expects stereo audio, got {channels} channels"
        )

    step = int(chunk_size * (1.0 - overlap))

    if step <= 0:
        raise ValueError("overlap must be < 1.0")

    output = torch.zeros(len(STEMS),channels,total_samples,dtype=torch.float32)

    weight = torch.zeros(total_samples, dtype=torch.float32)
    window = torch.hann_window(chunk_size,dtype=torch.float32)
    positions = list(range(0, max(total_samples - chunk_size, 0) + 1, step))

    if not positions or positions[-1] + chunk_size < total_samples:
        positions.append(max(total_samples - chunk_size, 0))

    for i, start in enumerate(positions):

        end = min(start + chunk_size, total_samples)

        chunk_len = end - start
        chunk = audio[:, start:end]

        if chunk_len < chunk_size:
            chunk = torch.nn.functional.pad(chunk,(0, chunk_size - chunk_len))

        chunk = chunk.unsqueeze(0).to(device)

        print(
            f"Chunk {i+1}/{len(positions)} "
            f"[{start / SAMPLE_RATE:.1f}s - {end / SAMPLE_RATE:.1f}s]",
            flush=True
        )

        if device.type == "cuda":
            with torch.autocast(device_type="cuda",dtype=torch.float16):
                prediction = model(chunk)
        else:
            prediction = model(chunk)

        prediction = prediction[0].float().cpu()
        prediction = prediction[:, :, :chunk_len]

        w = window[:chunk_len]
        output[:, :, start:end] += prediction * w
        weight[start:end] += w

        del chunk, prediction

    weight = weight.clamp_min(1e-8)
    output /= weight[None, None, :]

    return output

def seperate_files(audio_path, output_dir_path):
    input_folder = Path(audio_path)
    output_folder = Path(output_dir_path)

    output_folder.mkdir(parents=True, exist_ok=True)

    files = sorted(input_folder.glob("*.wav"))

    print(f"Found {len(files)} files.")

    if not files:
        print("no audio files found")
        return

    if INFERENCE_TIMES_PATH.exists() and INFERENCE_TIMES_PATH.stat().st_size > 0:
        try:
            with open(INFERENCE_TIMES_PATH, "r") as f:
                inference_times = json.load(f)
        except json.JSONDecodeError:
            print(
                "Warning: invalid inference_times.json. Starting fresh.",
                flush=True
            )
            inference_times = {}
    else:
        inference_times = {}

    for idx, file in enumerate(files):
        folder_name = f"track_{idx+1:03d}"
        track_output_dir = output_folder / folder_name

        track_output_dir.mkdir(parents=True, exist_ok=True)

        print(f"Processing {file} to {track_output_dir}", flush=True)

        audio = load_audio(file)

        if torch.cuda.is_available():
            torch.cuda.synchronize()

        start_time = time.perf_counter()

        separated = separate_audio(audio, model=model)

        if torch.cuda.is_available():
            torch.cuda.synchronize()

        inference_time = time.perf_counter() - start_time
        inference_times[folder_name] = inference_time

        print(
            f"Inference time for {folder_name}: {inference_time:.2f} sec",
            flush=True
        )

        temp_path = INFERENCE_TIMES_PATH.with_suffix(".json.tmp")

        with open(temp_path, "w") as f:
            json.dump(inference_times, f, indent=2)

        temp_path.replace(INFERENCE_TIMES_PATH)

        for i in range(len(STEMS)):
            output_path = track_output_dir / f"{STEMS[i]}.wav"

            sf.write(
                str(output_path),
                separated[i].cpu().numpy().T,
                SAMPLE_RATE
            )

            print(f"Saved: {output_path}", flush=True)

        print("--------------------------------------", flush=True)

if __name__ == "__main__":
  seperate_files(AUDIO_DIR_PATH, OUTPUT_DIR_PATH)